/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.CatolicaBank;

import com.mycompany.CatolicaBank.model.Conta;
import com.mycompany.CatolicaBank.model.ContaCorrente;
import com.mycompany.CatolicaBank.model.ContaPoupanca;
import com.mycompany.CatolicaBank.model.ContaUniversitaria;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author duduy
 */
public class CatolicaBankJFrame extends javax.swing.JFrame {
ContaCorrente proprietario = new ContaCorrente(0000, 000000, "Luís", 1);
    /**
     * Creates new form CatolicaBankJFrame
     */
    public CatolicaBankJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tab_historico = new javax.swing.JPanel();
        lb_historico = new javax.swing.JLabel();
        tab_contas = new javax.swing.JPanel();
        lb_contas = new javax.swing.JLabel();
        tab_menu = new javax.swing.JPanel();
        lb_menu = new javax.swing.JLabel();
        tab_about = new javax.swing.JPanel();
        lb_about = new javax.swing.JLabel();
        screen = new javax.swing.JPanel();
        jp_menu = new javax.swing.JPanel();
        jb_saque = new javax.swing.JButton();
        jb_deposito = new javax.swing.JButton();
        jb_transferencia = new javax.swing.JButton();
        jtf_deposito = new javax.swing.JTextField();
        jtf_saque = new javax.swing.JTextField();
        jlb_numeroConta = new javax.swing.JLabel();
        jtf_contaDestino = new javax.swing.JTextField();
        jlb_valor = new javax.swing.JLabel();
        jtf_valorTransferido = new javax.swing.JTextField();
        jlb_nome = new javax.swing.JLabel();
        jtf_nome = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jcb_tipoConta = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jp_about = new javax.swing.JPanel();
        jp_contas = new javax.swing.JPanel();
        jp_historico = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebar.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CatolicaBank");

        tab_historico.setBackground(new java.awt.Color(204, 204, 255));
        tab_historico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_historicoMouseClicked(evt);
            }
        });

        lb_historico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lb_historico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_historico.setText("Historico");
        lb_historico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_historicoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tab_historicoLayout = new javax.swing.GroupLayout(tab_historico);
        tab_historico.setLayout(tab_historicoLayout);
        tab_historicoLayout.setHorizontalGroup(
            tab_historicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_historico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tab_historicoLayout.setVerticalGroup(
            tab_historicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_historicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_historico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tab_contas.setBackground(new java.awt.Color(204, 204, 255));
        tab_contas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_contasMouseClicked(evt);
            }
        });

        lb_contas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lb_contas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_contas.setText("Contas");
        lb_contas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_contasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tab_contasLayout = new javax.swing.GroupLayout(tab_contas);
        tab_contas.setLayout(tab_contasLayout);
        tab_contasLayout.setHorizontalGroup(
            tab_contasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_contas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tab_contasLayout.setVerticalGroup(
            tab_contasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_contasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_contas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab_menu.setBackground(new java.awt.Color(204, 204, 255));
        tab_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_menuMouseClicked(evt);
            }
        });

        lb_menu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lb_menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_menu.setText("Menu");
        lb_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_menuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tab_menuLayout = new javax.swing.GroupLayout(tab_menu);
        tab_menu.setLayout(tab_menuLayout);
        tab_menuLayout.setHorizontalGroup(
            tab_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tab_menuLayout.setVerticalGroup(
            tab_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_menu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab_about.setBackground(new java.awt.Color(204, 204, 255));
        tab_about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_aboutMouseClicked(evt);
            }
        });

        lb_about.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lb_about.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_about.setText("About");
        lb_about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_aboutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tab_aboutLayout = new javax.swing.GroupLayout(tab_about);
        tab_about.setLayout(tab_aboutLayout);
        tab_aboutLayout.setHorizontalGroup(
            tab_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_about, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tab_aboutLayout.setVerticalGroup(
            tab_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_aboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_about)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_historico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab_contas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab_about, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(tab_historico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tab_contas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tab_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tab_about, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        screen.setBackground(new java.awt.Color(255, 255, 255));

        jp_menu.setBackground(new java.awt.Color(255, 255, 255));

        jb_saque.setBackground(new java.awt.Color(204, 204, 255));
        jb_saque.setText("saque");

        jb_deposito.setBackground(new java.awt.Color(204, 204, 255));
        jb_deposito.setText("deposito");

        jb_transferencia.setBackground(new java.awt.Color(204, 204, 255));
        jb_transferencia.setText("transferir");
        jb_transferencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_transferenciaMouseClicked(evt);
            }
        });

        jtf_deposito.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtf_deposito.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_saque.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtf_saque.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlb_numeroConta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlb_numeroConta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb_numeroConta.setText("Digite o numero da conta destino");

        jtf_contaDestino.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtf_contaDestino.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlb_valor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlb_valor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb_valor.setText("Valor");

        jtf_valorTransferido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtf_valorTransferido.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlb_nome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlb_nome.setText("Nome do proprietario da conta destino");

        jtf_nome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jcb_tipoConta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcb_tipoConta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Conta Corrente\t", "Conta Poupanca", "Conta Universitária" }));
        jcb_tipoConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_tipoContaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tipo da conta");

        javax.swing.GroupLayout jp_menuLayout = new javax.swing.GroupLayout(jp_menu);
        jp_menu.setLayout(jp_menuLayout);
        jp_menuLayout.setHorizontalGroup(
            jp_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_menuLayout.createSequentialGroup()
                        .addGroup(jp_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_menuLayout.createSequentialGroup()
                                .addGroup(jp_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_deposito)
                                    .addComponent(jtf_saque))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jp_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jb_saque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jb_deposito, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(jp_menuLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jp_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtf_contaDestino)
                                .addComponent(jlb_numeroConta, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
                            .addComponent(jtf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_nome))
                        .addGap(72, 72, 72)
                        .addGroup(jp_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtf_valorTransferido, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                            .addComponent(jlb_valor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcb_tipoConta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(20, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_menuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_transferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
        );
        jp_menuLayout.setVerticalGroup(
            jp_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_menuLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jp_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_deposito, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_deposito, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_saque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtf_saque, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_nome)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_tipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jp_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_numeroConta)
                    .addComponent(jlb_valor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_contaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_valorTransferido, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jb_transferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jp_about.setPreferredSize(new java.awt.Dimension(626, 463));

        javax.swing.GroupLayout jp_aboutLayout = new javax.swing.GroupLayout(jp_about);
        jp_about.setLayout(jp_aboutLayout);
        jp_aboutLayout.setHorizontalGroup(
            jp_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );
        jp_aboutLayout.setVerticalGroup(
            jp_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        jp_contas.setPreferredSize(new java.awt.Dimension(626, 463));

        javax.swing.GroupLayout jp_contasLayout = new javax.swing.GroupLayout(jp_contas);
        jp_contas.setLayout(jp_contasLayout);
        jp_contasLayout.setHorizontalGroup(
            jp_contasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );
        jp_contasLayout.setVerticalGroup(
            jp_contasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        jp_historico.setBackground(new java.awt.Color(255, 255, 255));
        jp_historico.setPreferredSize(new java.awt.Dimension(626, 463));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Primeiro Nome", "Ultimo nome", "Numero da conta", "Valor Transferido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jp_historicoLayout = new javax.swing.GroupLayout(jp_historico);
        jp_historico.setLayout(jp_historicoLayout);
        jp_historicoLayout.setHorizontalGroup(
            jp_historicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
        );
        jp_historicoLayout.setVerticalGroup(
            jp_historicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout screenLayout = new javax.swing.GroupLayout(screen);
        screen.setLayout(screenLayout);
        screenLayout.setHorizontalGroup(
            screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_historico, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
            .addGroup(screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp_contas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE))
            .addGroup(screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp_menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp_about, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE))
        );
        screenLayout.setVerticalGroup(
            screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_historico, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
            .addGroup(screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp_contas, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE))
            .addGroup(screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp_about, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(screen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(screen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tab_historicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_historicoMouseClicked
        ArrayList<Conta> contas = new ArrayList();
        menuClick(1);
        
       
;
        
    }//GEN-LAST:event_tab_historicoMouseClicked

    private void tab_contasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_contasMouseClicked
       menuClick(2);
    }//GEN-LAST:event_tab_contasMouseClicked

    private void tab_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_menuMouseClicked
        menuClick(3);
    }//GEN-LAST:event_tab_menuMouseClicked

    private void tab_aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_aboutMouseClicked
        menuClick(4);
    }//GEN-LAST:event_tab_aboutMouseClicked

    private void lb_historicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_historicoMouseClicked
        menuClick(1);
    }//GEN-LAST:event_lb_historicoMouseClicked

    private void lb_contasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_contasMouseClicked
       menuClick(2);
    }//GEN-LAST:event_lb_contasMouseClicked

    private void lb_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_menuMouseClicked
        menuClick(3);
    }//GEN-LAST:event_lb_menuMouseClicked

    private void lb_aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_aboutMouseClicked
        menuClick(4);
    }//GEN-LAST:event_lb_aboutMouseClicked

    private void jcb_tipoContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_tipoContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_tipoContaActionPerformed

    private void jb_transferenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_transferenciaMouseClicked
        String nome = "";
        int contaDestino = 0;
        String valorTransferido = "";
        double quantia = 0;
        if(jtf_nome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo de nome deve estar preenchido", "Input Error", JOptionPane.WARNING_MESSAGE);
        } else{
            nome = jtf_nome.getText();
        }
        if(jtf_contaDestino.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo numero da conta deve estar preenchido", "Input Error", JOptionPane.WARNING_MESSAGE);
        }else {
            try {
            contaDestino = Integer.parseInt(jtf_contaDestino.getText());
            } catch(NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "O campo numero da conta deve ser um numero", "Input Error", JOptionPane.WARNING_MESSAGE);
            }
        }
        if(jtf_valorTransferido.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo valor deve estar preenchido", "Input Error", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                quantia = Double.parseDouble(jtf_valorTransferido.getText());
            } catch(NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "O campo valor deve ser um numero", "Input Error", JOptionPane.WARNING_MESSAGE);
            }
        }
        if (null != jcb_tipoConta.getSelectedItem().toString()) switch (jcb_tipoConta.getSelectedItem().toString()) {
        case "Conta Corrente":
            ContaCorrente contacorrente = new ContaCorrente(0000, contaDestino, nome, 1);
            proprietario.transfere(contacorrente, quantia);
            addTransferToTable(contacorrente);
            break;
        case "Conta Poupança":
            ContaPoupanca contapoupanca = new ContaPoupanca(0000, contaDestino, nome, 2);
            proprietario.transfere(contapoupanca, quantia);
            addTransferToTable(contapoupanca);
            break; 
        case "Conta Universitária":
            ContaUniversitaria contauniversitaria = new ContaUniversitaria(0000, contaDestino, nome, 3);
            proprietario.transfere(contauniversitaria, quantia);
            addTransferToTable(contauniversitaria);
            break;
        default:
            break;
    }
        
    }//GEN-LAST:event_jb_transferenciaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatolicaBankJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatolicaBankJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatolicaBankJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatolicaBankJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CatolicaBankJFrame().setVisible(true);
        });
    }
    
    public void addTransferToTable(Conta conta) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {conta.getNome(), conta.getNumero(), conta.getSaldo(), conta.getTipo()});
    }
    
    public void menuClick(int opt) {
        switch(opt) {
            case 1:
                jp_historico.setVisible(true);
                jp_contas.setVisible(false);
                jp_menu.setVisible(false);
                jp_about.setVisible(false);
                tab_historico.setBackground(Color.white);
                tab_contas.setBackground(new Color(204,204,255));
                tab_menu.setBackground(new Color(204,204,255));
                tab_about.setBackground(new Color(204,204,255));
                break;
            case 2:
                jp_historico.setVisible(false);
                jp_contas.setVisible(true);
                jp_menu.setVisible(false);
                jp_about.setVisible(false);
                tab_historico.setBackground(new Color(204,204,255));
                tab_contas.setBackground(Color.white);
                tab_menu.setBackground(new Color(204,204,255));
                tab_about.setBackground(new Color(204,204,255));
                break;
            case 3:
                jp_historico.setVisible(false);
                jp_contas.setVisible(false);
                jp_menu.setVisible(true);
                jp_about.setVisible(false);
                tab_historico.setBackground(new Color(204,204,255));
                tab_contas.setBackground(new Color(204,204,255));
                tab_menu.setBackground(Color.white);
                tab_about.setBackground(new Color(204,204,255));
                break;
            case 4:
                jp_historico.setVisible(false);
                jp_contas.setVisible(false);
                jp_menu.setVisible(false);
                jp_about.setVisible(true);
                tab_historico.setBackground(new Color(204,204,255));
                tab_contas.setBackground(new Color(204,204,255));
                tab_menu.setBackground(new Color(204,204,255));
                tab_about.setBackground(Color.white);
                break;
            case 5:
                jp_historico.setVisible(false);
                jp_contas.setVisible(false);
                jp_menu.setVisible(false);
                jp_about.setVisible(false);
                break;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jb_deposito;
    private javax.swing.JButton jb_saque;
    private javax.swing.JButton jb_transferencia;
    private javax.swing.JComboBox<String> jcb_tipoConta;
    private javax.swing.JLabel jlb_nome;
    private javax.swing.JLabel jlb_numeroConta;
    private javax.swing.JLabel jlb_valor;
    private javax.swing.JPanel jp_about;
    private javax.swing.JPanel jp_contas;
    private javax.swing.JPanel jp_historico;
    private javax.swing.JPanel jp_menu;
    private javax.swing.JTextField jtf_contaDestino;
    private javax.swing.JTextField jtf_deposito;
    private javax.swing.JTextField jtf_nome;
    private javax.swing.JTextField jtf_saque;
    private javax.swing.JTextField jtf_valorTransferido;
    private javax.swing.JLabel lb_about;
    private javax.swing.JLabel lb_contas;
    private javax.swing.JLabel lb_historico;
    private javax.swing.JLabel lb_menu;
    private javax.swing.JPanel screen;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel tab_about;
    private javax.swing.JPanel tab_contas;
    private javax.swing.JPanel tab_historico;
    private javax.swing.JPanel tab_menu;
    // End of variables declaration//GEN-END:variables
}
